package com.ajit.callai;
import android.app.*; import android.content.*; import android.media.*; import android.os.*; import android.speech.*; import android.speech.tts.*; import android.telecom.*; import java.util.*;
public class CallService extends InCallService {
 private Call call; private TextToSpeech tts; private SpeechRecognizer sr; private AudioManager audio; private boolean running;
 @Override public void onCallAdded(Call c){super.onCallAdded(c);call=c; if(!AppState.enabled(this))return; notifyUser("Incoming call: "+AppState.number(this)); if(AppState.autoAnswer(this)) new Handler().postDelayed(()->startAgent(),900);}
 void startAgent(){if(call==null)return;try{call.answer(VideoProfile.STATE_AUDIO_ONLY);}catch(Exception ignored){} audio=(AudioManager)getSystemService(AUDIO_SERVICE); if(audio!=null){audio.setMode(AudioManager.MODE_IN_COMMUNICATION);audio.setSpeakerphoneOn(true);} tts=new TextToSpeech(getApplicationContext(),st->{if(st==TextToSpeech.SUCCESS){tts.setLanguage(new Locale("hi","IN"));speak(AppState.instruction(this));}});}
 void speak(String text){if(tts!=null){tts.speak(text,TextToSpeech.QUEUE_FLUSH,null,"call_ai");new Handler().postDelayed(this::listen,Math.max(1800,text.length()*65L));}}
 void listen(){if(call==null||!AppState.enabled(this))return;if(sr!=null)sr.destroy();sr=SpeechRecognizer.createSpeechRecognizer(getApplicationContext());sr.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onError(int e){new Handler().postDelayed(()->listen(),700);}public void onResults(Bundle b){ArrayList<String> a=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);String s=a==null||a.isEmpty()?"":a.get(0);if(s.contains("बंद")||s.toLowerCase().contains("hang up")||s.toLowerCase().contains("end call")){hangup();return;}String reply=Brain.reply(s);speak(reply);}public void onPartialResults(Bundle b){}public void onEvent(int t,Bundle b){}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE, "hi-IN");i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,false);sr.startListening(i);}
 void hangup(){try{if(call!=null)call.disconnect();}catch(Exception ignored){}stopAgent();}
 void stopAgent(){running=false;if(sr!=null){sr.cancel();sr.destroy();sr=null;}if(tts!=null){tts.stop();tts.shutdown();tts=null;}if(audio!=null){audio.setSpeakerphoneOn(false);audio.setMode(AudioManager.MODE_NORMAL);}}
 @Override public void onCallRemoved(Call c){if(c==call){stopAgent();call=null;notifyUser("Call ended");}super.onCallRemoved(c);}
 void notifyUser(String s){NotificationManager n=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);String ch="calls";if(Build.VERSION.SDK_INT>=26)n.createNotificationChannel(new NotificationChannel(ch,"Calls",NotificationManager.IMPORTANCE_HIGH));n.notify(7,new Notification.Builder(this,ch).setSmallIcon(android.R.drawable.sym_action_call).setContentTitle("Call AI Assistant").setContentText(s).setAutoCancel(true).build());}
}
